[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "never"

[env]
PYTHON_VERSION = "3.11"
PORT = "8000" 