[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
ENVIRONMENT = "production"

[variables]
CORS_ORIGINS = "https://goodtext-ai-cleaner.netlify.app,https://*.railway.app" 